### ISSUE TITLE
React Group Project

### ISSUE THREAD

**Issue by demesameneshoa** [Gh-Reza/space-traveler-s-hub#25]
### We have completed setting up our Kanban View for our react group project
- Our project link is below
https://github.com/Gh-Reza/space-traveler-s-hub/projects/2 
- There are two students in this group

**Comment by OyePriscilla** [comment]
Hi @demesameneshoa and @Gh-Reza , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Set up kanban board ✔️ 
Tasks assigned fairly to the group members ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by demesameneshoa** [comment]
@OyePriscilla  Thank you for the feedback!
